//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEI.SiebelIntegrationSEI {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI", ConfigurationName="SiebelIntegrationSEI.SEI_spcIntegration_spcExchange")]
    public interface SEI_spcIntegration_spcExchange {
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:DeleteAppointment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DeleteAppointmentOut")]
        SEI.SiebelIntegrationSEI.AppointmentTopElmt DeleteAppointment(string ExchangeId, string SiebelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:DeleteAppointment", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="DeleteAppointmentOut")]
        System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.AppointmentTopElmt> DeleteAppointmentAsync(string ExchangeId, string SiebelId);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:InsertSEIUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SEIUserOut")]
        SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt InsertSEIUser(string pUserid, string pEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:InsertSEIUser", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SEIUserOut")]
        System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt> InsertSEIUserAsync(string pUserid, string pEmail);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:DeleteSEIUser", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SEIUserOut")]
        SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt DeleteSEIUser(string pUserid);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:DeleteSEIUser", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SEIUserOut")]
        System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt> DeleteSEIUserAsync(string pUserid);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:ChangeActStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SEIUserOut")]
        SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt ChangeActStatus(string pActionId, string pNewStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:ChangeActStatus", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="SEIUserOut")]
        System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt> ChangeActStatusAsync(string pActionId, string pNewStatus);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:NewAppointment", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ExchangeAppointmentOut")]
        SEI.SiebelIntegrationSEI.AppointmentTopElmt NewAppointment(SEI.SiebelIntegrationSEI.AppointmentTopElmt1 ExchangeAppointmentIn);
        
        [System.ServiceModel.OperationContractAttribute(Action="rpc/http://siebel.com/marketing/IntegrationSEI:NewAppointment", ReplyAction="*")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="ExchangeAppointmentOut")]
        System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.AppointmentTopElmt> NewAppointmentAsync(SEI.SiebelIntegrationSEI.AppointmentTopElmt1 ExchangeAppointmentIn);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/SEI%20AppointmentExchangeOut")]
    public partial class AppointmentTopElmt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Appointment appointmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Appointment Appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
                this.RaisePropertyChanged("Appointment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/SEI%20AppointmentExchangeOut")]
    public partial class Appointment : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorTextField;
        
        private string siebelIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("ErrorText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SiebelId {
            get {
                return this.siebelIdField;
            }
            set {
                this.siebelIdField = value;
                this.RaisePropertyChanged("SiebelId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class UniqueBody : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string bodyTypeField;
        
        private string isTruncatedField;
        
        private string textField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string BodyType {
            get {
                return this.bodyTypeField;
            }
            set {
                this.bodyTypeField = value;
                this.RaisePropertyChanged("BodyType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string IsTruncated {
            get {
                return this.isTruncatedField;
            }
            set {
                this.isTruncatedField = value;
                this.RaisePropertyChanged("IsTruncated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Text {
            get {
                return this.textField;
            }
            set {
                this.textField = value;
                this.RaisePropertyChanged("Text");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class StartTimeZone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Offset offsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Offset Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("Offset");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Offset : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string daysField;
        
        private string hoursField;
        
        private string minutesField;
        
        private string secondsField;
        
        private string millisecondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
                this.RaisePropertyChanged("Days");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
                this.RaisePropertyChanged("Hours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
                this.RaisePropertyChanged("Minutes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
                this.RaisePropertyChanged("Seconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Milliseconds {
            get {
                return this.millisecondsField;
            }
            set {
                this.millisecondsField = value;
                this.RaisePropertyChanged("Milliseconds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Recurrence : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Preview : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class PolicyTag : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Organizer : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string idField;
        
        private string mailboxTypeField;
        
        private string nameField;
        
        private string routingTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MailboxType {
            get {
                return this.mailboxTypeField;
            }
            set {
                this.mailboxTypeField = value;
                this.RaisePropertyChanged("MailboxType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RoutingType {
            get {
                return this.routingTypeField;
            }
            set {
                this.routingTypeField = value;
                this.RaisePropertyChanged("RoutingType");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Attendee : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string addressField;
        
        private string idField;
        
        private string mailboxTypeField;
        
        private string nameField;
        
        private string routingTypeField;
        
        private string responseTypeField;
        
        private string lastResponseTimeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Address {
            get {
                return this.addressField;
            }
            set {
                this.addressField = value;
                this.RaisePropertyChanged("Address");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MailboxType {
            get {
                return this.mailboxTypeField;
            }
            set {
                this.mailboxTypeField = value;
                this.RaisePropertyChanged("MailboxType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string RoutingType {
            get {
                return this.routingTypeField;
            }
            set {
                this.routingTypeField = value;
                this.RaisePropertyChanged("RoutingType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string ResponseType {
            get {
                return this.responseTypeField;
            }
            set {
                this.responseTypeField = value;
                this.RaisePropertyChanged("ResponseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string LastResponseTime {
            get {
                return this.lastResponseTimeField;
            }
            set {
                this.lastResponseTimeField = value;
                this.RaisePropertyChanged("LastResponseTime");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class OnlineMeetingSettings : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class ModifiedOccurrences : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class MimeContent : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string stringElementField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string StringElement {
            get {
                return this.stringElementField;
            }
            set {
                this.stringElementField = value;
                this.RaisePropertyChanged("StringElement");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class LastOccurrence : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class InternetMessageHeaders : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class IconIndex : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Flag : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class FirstOccurrence : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class ExtendedProperty : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class EntityExtractionResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class EnhancedLocation : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class EndTimeZone : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Offset offsetField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Offset Offset {
            get {
                return this.offsetField;
            }
            set {
                this.offsetField = value;
                this.RaisePropertyChanged("Offset");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Duration : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string daysField;
        
        private string hoursField;
        
        private string minutesField;
        
        private string secondsField;
        
        private string millisecondsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
                this.RaisePropertyChanged("Days");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
                this.RaisePropertyChanged("Hours");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
                this.RaisePropertyChanged("Minutes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
                this.RaisePropertyChanged("Seconds");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string Milliseconds {
            get {
                return this.millisecondsField;
            }
            set {
                this.millisecondsField = value;
                this.RaisePropertyChanged("Milliseconds");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class DeletedOccurrences : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class ConflictingMeetings : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Category : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nameField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Value {
            get {
                return this.valueField;
            }
            set {
                this.valueField = value;
                this.RaisePropertyChanged("Value");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Attachments : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class ArchiveTag : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class AdjacentMeetings : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="Appointment", Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class Appointment1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string adjacentMeetingCountField;
        
        private AdjacentMeetings adjacentMeetingsField;
        
        private string allowNewTimeProposalField;
        
        private string appointmentReplyTimeField;
        
        private string appointmentSequenceNumberField;
        
        private string appointmentStateField;
        
        private string appointmentTypeField;
        
        private ArchiveTag archiveTagField;
        
        private Attachments attachmentsField;
        
        private string bodyField;
        
        private Category[] categoriesField;
        
        private string conferenceTypeField;
        
        private string conflictingMeetingCountField;
        
        private ConflictingMeetings conflictingMeetingsField;
        
        private string conversationIdField;
        
        private string cultureField;
        
        private string dateTimeCreatedField;
        
        private string dateTimeReceivedField;
        
        private string dateTimeSentField;
        
        private DeletedOccurrences deletedOccurrencesField;
        
        private string displayCcField;
        
        private string displayToField;
        
        private Duration durationField;
        
        private string endField;
        
        private EndTimeZone endTimeZoneField;
        
        private EnhancedLocation enhancedLocationField;
        
        private EntityExtractionResult[] entityExtractionResultField;
        
        private ExtendedProperty[] extendedPropertiesField;
        
        private FirstOccurrence firstOccurrenceField;
        
        private Flag flagField;
        
        private string hasAttachmentsField;
        
        private string iCalDateTimeStampField;
        
        private string iCalRecurrenceIdField;
        
        private string iCalUidField;
        
        private IconIndex iconIndexField;
        
        private string idField;
        
        private string importanceField;
        
        private string inReplyToField;
        
        private string instanceKeyField;
        
        private InternetMessageHeaders internetMessageHeadersField;
        
        private string isAllDayEventField;
        
        private string isAssociatedField;
        
        private string isAttachmentField;
        
        private string isCancelledField;
        
        private string isDirtyField;
        
        private string isDraftField;
        
        private string isFromMeField;
        
        private string isMeetingField;
        
        private string isNewField;
        
        private string isOnlineMeetingField;
        
        private string isRecurringField;
        
        private string isReminderSetField;
        
        private string isResendField;
        
        private string isResponseRequestedField;
        
        private string isSubmittedField;
        
        private string isUnmodifiedField;
        
        private string itemClassField;
        
        private string joinOnlineMeetingUrlField;
        
        private string lastModifiedNameField;
        
        private string lastModifiedTimeField;
        
        private LastOccurrence lastOccurrenceField;
        
        private string legacyFreeBusyStatusField;
        
        private string locationField;
        
        private string meetingRequestWasSentField;
        
        private string meetingWorkspaceUrlField;
        
        private MimeContent mimeContentField;
        
        private ModifiedOccurrences modifiedOccurrencesField;
        
        private string myResponseTypeField;
        
        private string netShowUrlField;
        
        private string normalizedBodyField;
        
        private OnlineMeetingSettings onlineMeetingSettingsField;
        
        private Attendee[] optionalAttendeesField;
        
        private Organizer organizerField;
        
        private string originalStartField;
        
        private string parentFolderIdField;
        
        private PolicyTag policyTagField;
        
        private Preview previewField;
        
        private Recurrence recurrenceField;
        
        private string reminderDueByField;
        
        private string reminderMinutesBeforeStartField;
        
        private Attendee[] requiredAttendeesField;
        
        private Attendee[] resourcesField;
        
        private string retentionDateField;
        
        private string schemaField;
        
        private string sensitivityField;
        
        private string sizeField;
        
        private string startField;
        
        private StartTimeZone startTimeZoneField;
        
        private string storeEntryIdField;
        
        private string subjectField;
        
        private string textBodyField;
        
        private string timeZoneField;
        
        private UniqueBody uniqueBodyField;
        
        private string webClientEditFormQueryStringField;
        
        private string webClientReadFormQueryStringField;
        
        private string whenField;
        
        private string allowedResponseActionsField;
        
        private string effectiveRightsField;
        
        private string isOrganizedField;
        
        private string localIdField;
        
        private string requestorIdField;
        
        private string requestorLoginField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AdjacentMeetingCount {
            get {
                return this.adjacentMeetingCountField;
            }
            set {
                this.adjacentMeetingCountField = value;
                this.RaisePropertyChanged("AdjacentMeetingCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AdjacentMeetings AdjacentMeetings {
            get {
                return this.adjacentMeetingsField;
            }
            set {
                this.adjacentMeetingsField = value;
                this.RaisePropertyChanged("AdjacentMeetings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AllowNewTimeProposal {
            get {
                return this.allowNewTimeProposalField;
            }
            set {
                this.allowNewTimeProposalField = value;
                this.RaisePropertyChanged("AllowNewTimeProposal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string AppointmentReplyTime {
            get {
                return this.appointmentReplyTimeField;
            }
            set {
                this.appointmentReplyTimeField = value;
                this.RaisePropertyChanged("AppointmentReplyTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AppointmentSequenceNumber {
            get {
                return this.appointmentSequenceNumberField;
            }
            set {
                this.appointmentSequenceNumberField = value;
                this.RaisePropertyChanged("AppointmentSequenceNumber");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AppointmentState {
            get {
                return this.appointmentStateField;
            }
            set {
                this.appointmentStateField = value;
                this.RaisePropertyChanged("AppointmentState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string AppointmentType {
            get {
                return this.appointmentTypeField;
            }
            set {
                this.appointmentTypeField = value;
                this.RaisePropertyChanged("AppointmentType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public ArchiveTag ArchiveTag {
            get {
                return this.archiveTagField;
            }
            set {
                this.archiveTagField = value;
                this.RaisePropertyChanged("ArchiveTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public Attachments Attachments {
            get {
                return this.attachmentsField;
            }
            set {
                this.attachmentsField = value;
                this.RaisePropertyChanged("Attachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Body {
            get {
                return this.bodyField;
            }
            set {
                this.bodyField = value;
                this.RaisePropertyChanged("Body");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=10)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Category[] Categories {
            get {
                return this.categoriesField;
            }
            set {
                this.categoriesField = value;
                this.RaisePropertyChanged("Categories");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public string ConferenceType {
            get {
                return this.conferenceTypeField;
            }
            set {
                this.conferenceTypeField = value;
                this.RaisePropertyChanged("ConferenceType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public string ConflictingMeetingCount {
            get {
                return this.conflictingMeetingCountField;
            }
            set {
                this.conflictingMeetingCountField = value;
                this.RaisePropertyChanged("ConflictingMeetingCount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public ConflictingMeetings ConflictingMeetings {
            get {
                return this.conflictingMeetingsField;
            }
            set {
                this.conflictingMeetingsField = value;
                this.RaisePropertyChanged("ConflictingMeetings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public string ConversationId {
            get {
                return this.conversationIdField;
            }
            set {
                this.conversationIdField = value;
                this.RaisePropertyChanged("ConversationId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public string Culture {
            get {
                return this.cultureField;
            }
            set {
                this.cultureField = value;
                this.RaisePropertyChanged("Culture");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public string DateTimeCreated {
            get {
                return this.dateTimeCreatedField;
            }
            set {
                this.dateTimeCreatedField = value;
                this.RaisePropertyChanged("DateTimeCreated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public string DateTimeReceived {
            get {
                return this.dateTimeReceivedField;
            }
            set {
                this.dateTimeReceivedField = value;
                this.RaisePropertyChanged("DateTimeReceived");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=18)]
        public string DateTimeSent {
            get {
                return this.dateTimeSentField;
            }
            set {
                this.dateTimeSentField = value;
                this.RaisePropertyChanged("DateTimeSent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=19)]
        public DeletedOccurrences DeletedOccurrences {
            get {
                return this.deletedOccurrencesField;
            }
            set {
                this.deletedOccurrencesField = value;
                this.RaisePropertyChanged("DeletedOccurrences");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=20)]
        public string DisplayCc {
            get {
                return this.displayCcField;
            }
            set {
                this.displayCcField = value;
                this.RaisePropertyChanged("DisplayCc");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=21)]
        public string DisplayTo {
            get {
                return this.displayToField;
            }
            set {
                this.displayToField = value;
                this.RaisePropertyChanged("DisplayTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=22)]
        public Duration Duration {
            get {
                return this.durationField;
            }
            set {
                this.durationField = value;
                this.RaisePropertyChanged("Duration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=23)]
        public string End {
            get {
                return this.endField;
            }
            set {
                this.endField = value;
                this.RaisePropertyChanged("End");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=24)]
        public EndTimeZone EndTimeZone {
            get {
                return this.endTimeZoneField;
            }
            set {
                this.endTimeZoneField = value;
                this.RaisePropertyChanged("EndTimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=25)]
        public EnhancedLocation EnhancedLocation {
            get {
                return this.enhancedLocationField;
            }
            set {
                this.enhancedLocationField = value;
                this.RaisePropertyChanged("EnhancedLocation");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("EntityExtractionResult", Order=26)]
        public EntityExtractionResult[] EntityExtractionResult {
            get {
                return this.entityExtractionResultField;
            }
            set {
                this.entityExtractionResultField = value;
                this.RaisePropertyChanged("EntityExtractionResult");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=27)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public ExtendedProperty[] ExtendedProperties {
            get {
                return this.extendedPropertiesField;
            }
            set {
                this.extendedPropertiesField = value;
                this.RaisePropertyChanged("ExtendedProperties");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=28)]
        public FirstOccurrence FirstOccurrence {
            get {
                return this.firstOccurrenceField;
            }
            set {
                this.firstOccurrenceField = value;
                this.RaisePropertyChanged("FirstOccurrence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=29)]
        public Flag Flag {
            get {
                return this.flagField;
            }
            set {
                this.flagField = value;
                this.RaisePropertyChanged("Flag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=30)]
        public string HasAttachments {
            get {
                return this.hasAttachmentsField;
            }
            set {
                this.hasAttachmentsField = value;
                this.RaisePropertyChanged("HasAttachments");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=31)]
        public string ICalDateTimeStamp {
            get {
                return this.iCalDateTimeStampField;
            }
            set {
                this.iCalDateTimeStampField = value;
                this.RaisePropertyChanged("ICalDateTimeStamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=32)]
        public string ICalRecurrenceId {
            get {
                return this.iCalRecurrenceIdField;
            }
            set {
                this.iCalRecurrenceIdField = value;
                this.RaisePropertyChanged("ICalRecurrenceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=33)]
        public string ICalUid {
            get {
                return this.iCalUidField;
            }
            set {
                this.iCalUidField = value;
                this.RaisePropertyChanged("ICalUid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=34)]
        public IconIndex IconIndex {
            get {
                return this.iconIndexField;
            }
            set {
                this.iconIndexField = value;
                this.RaisePropertyChanged("IconIndex");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=35)]
        public string Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=36)]
        public string Importance {
            get {
                return this.importanceField;
            }
            set {
                this.importanceField = value;
                this.RaisePropertyChanged("Importance");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=37)]
        public string InReplyTo {
            get {
                return this.inReplyToField;
            }
            set {
                this.inReplyToField = value;
                this.RaisePropertyChanged("InReplyTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=38)]
        public string InstanceKey {
            get {
                return this.instanceKeyField;
            }
            set {
                this.instanceKeyField = value;
                this.RaisePropertyChanged("InstanceKey");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=39)]
        public InternetMessageHeaders InternetMessageHeaders {
            get {
                return this.internetMessageHeadersField;
            }
            set {
                this.internetMessageHeadersField = value;
                this.RaisePropertyChanged("InternetMessageHeaders");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=40)]
        public string IsAllDayEvent {
            get {
                return this.isAllDayEventField;
            }
            set {
                this.isAllDayEventField = value;
                this.RaisePropertyChanged("IsAllDayEvent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=41)]
        public string IsAssociated {
            get {
                return this.isAssociatedField;
            }
            set {
                this.isAssociatedField = value;
                this.RaisePropertyChanged("IsAssociated");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=42)]
        public string IsAttachment {
            get {
                return this.isAttachmentField;
            }
            set {
                this.isAttachmentField = value;
                this.RaisePropertyChanged("IsAttachment");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=43)]
        public string IsCancelled {
            get {
                return this.isCancelledField;
            }
            set {
                this.isCancelledField = value;
                this.RaisePropertyChanged("IsCancelled");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=44)]
        public string IsDirty {
            get {
                return this.isDirtyField;
            }
            set {
                this.isDirtyField = value;
                this.RaisePropertyChanged("IsDirty");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=45)]
        public string IsDraft {
            get {
                return this.isDraftField;
            }
            set {
                this.isDraftField = value;
                this.RaisePropertyChanged("IsDraft");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=46)]
        public string IsFromMe {
            get {
                return this.isFromMeField;
            }
            set {
                this.isFromMeField = value;
                this.RaisePropertyChanged("IsFromMe");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=47)]
        public string IsMeeting {
            get {
                return this.isMeetingField;
            }
            set {
                this.isMeetingField = value;
                this.RaisePropertyChanged("IsMeeting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=48)]
        public string IsNew {
            get {
                return this.isNewField;
            }
            set {
                this.isNewField = value;
                this.RaisePropertyChanged("IsNew");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=49)]
        public string IsOnlineMeeting {
            get {
                return this.isOnlineMeetingField;
            }
            set {
                this.isOnlineMeetingField = value;
                this.RaisePropertyChanged("IsOnlineMeeting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=50)]
        public string IsRecurring {
            get {
                return this.isRecurringField;
            }
            set {
                this.isRecurringField = value;
                this.RaisePropertyChanged("IsRecurring");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=51)]
        public string IsReminderSet {
            get {
                return this.isReminderSetField;
            }
            set {
                this.isReminderSetField = value;
                this.RaisePropertyChanged("IsReminderSet");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=52)]
        public string IsResend {
            get {
                return this.isResendField;
            }
            set {
                this.isResendField = value;
                this.RaisePropertyChanged("IsResend");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=53)]
        public string IsResponseRequested {
            get {
                return this.isResponseRequestedField;
            }
            set {
                this.isResponseRequestedField = value;
                this.RaisePropertyChanged("IsResponseRequested");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=54)]
        public string IsSubmitted {
            get {
                return this.isSubmittedField;
            }
            set {
                this.isSubmittedField = value;
                this.RaisePropertyChanged("IsSubmitted");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=55)]
        public string IsUnmodified {
            get {
                return this.isUnmodifiedField;
            }
            set {
                this.isUnmodifiedField = value;
                this.RaisePropertyChanged("IsUnmodified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=56)]
        public string ItemClass {
            get {
                return this.itemClassField;
            }
            set {
                this.itemClassField = value;
                this.RaisePropertyChanged("ItemClass");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=57)]
        public string JoinOnlineMeetingUrl {
            get {
                return this.joinOnlineMeetingUrlField;
            }
            set {
                this.joinOnlineMeetingUrlField = value;
                this.RaisePropertyChanged("JoinOnlineMeetingUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=58)]
        public string LastModifiedName {
            get {
                return this.lastModifiedNameField;
            }
            set {
                this.lastModifiedNameField = value;
                this.RaisePropertyChanged("LastModifiedName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=59)]
        public string LastModifiedTime {
            get {
                return this.lastModifiedTimeField;
            }
            set {
                this.lastModifiedTimeField = value;
                this.RaisePropertyChanged("LastModifiedTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=60)]
        public LastOccurrence LastOccurrence {
            get {
                return this.lastOccurrenceField;
            }
            set {
                this.lastOccurrenceField = value;
                this.RaisePropertyChanged("LastOccurrence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=61)]
        public string LegacyFreeBusyStatus {
            get {
                return this.legacyFreeBusyStatusField;
            }
            set {
                this.legacyFreeBusyStatusField = value;
                this.RaisePropertyChanged("LegacyFreeBusyStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=62)]
        public string Location {
            get {
                return this.locationField;
            }
            set {
                this.locationField = value;
                this.RaisePropertyChanged("Location");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=63)]
        public string MeetingRequestWasSent {
            get {
                return this.meetingRequestWasSentField;
            }
            set {
                this.meetingRequestWasSentField = value;
                this.RaisePropertyChanged("MeetingRequestWasSent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=64)]
        public string MeetingWorkspaceUrl {
            get {
                return this.meetingWorkspaceUrlField;
            }
            set {
                this.meetingWorkspaceUrlField = value;
                this.RaisePropertyChanged("MeetingWorkspaceUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=65)]
        public MimeContent MimeContent {
            get {
                return this.mimeContentField;
            }
            set {
                this.mimeContentField = value;
                this.RaisePropertyChanged("MimeContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=66)]
        public ModifiedOccurrences ModifiedOccurrences {
            get {
                return this.modifiedOccurrencesField;
            }
            set {
                this.modifiedOccurrencesField = value;
                this.RaisePropertyChanged("ModifiedOccurrences");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=67)]
        public string MyResponseType {
            get {
                return this.myResponseTypeField;
            }
            set {
                this.myResponseTypeField = value;
                this.RaisePropertyChanged("MyResponseType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=68)]
        public string NetShowUrl {
            get {
                return this.netShowUrlField;
            }
            set {
                this.netShowUrlField = value;
                this.RaisePropertyChanged("NetShowUrl");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=69)]
        public string NormalizedBody {
            get {
                return this.normalizedBodyField;
            }
            set {
                this.normalizedBodyField = value;
                this.RaisePropertyChanged("NormalizedBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=70)]
        public OnlineMeetingSettings OnlineMeetingSettings {
            get {
                return this.onlineMeetingSettingsField;
            }
            set {
                this.onlineMeetingSettingsField = value;
                this.RaisePropertyChanged("OnlineMeetingSettings");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=71)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Attendee[] OptionalAttendees {
            get {
                return this.optionalAttendeesField;
            }
            set {
                this.optionalAttendeesField = value;
                this.RaisePropertyChanged("OptionalAttendees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=72)]
        public Organizer Organizer {
            get {
                return this.organizerField;
            }
            set {
                this.organizerField = value;
                this.RaisePropertyChanged("Organizer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=73)]
        public string OriginalStart {
            get {
                return this.originalStartField;
            }
            set {
                this.originalStartField = value;
                this.RaisePropertyChanged("OriginalStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=74)]
        public string ParentFolderId {
            get {
                return this.parentFolderIdField;
            }
            set {
                this.parentFolderIdField = value;
                this.RaisePropertyChanged("ParentFolderId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=75)]
        public PolicyTag PolicyTag {
            get {
                return this.policyTagField;
            }
            set {
                this.policyTagField = value;
                this.RaisePropertyChanged("PolicyTag");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=76)]
        public Preview Preview {
            get {
                return this.previewField;
            }
            set {
                this.previewField = value;
                this.RaisePropertyChanged("Preview");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=77)]
        public Recurrence Recurrence {
            get {
                return this.recurrenceField;
            }
            set {
                this.recurrenceField = value;
                this.RaisePropertyChanged("Recurrence");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=78)]
        public string ReminderDueBy {
            get {
                return this.reminderDueByField;
            }
            set {
                this.reminderDueByField = value;
                this.RaisePropertyChanged("ReminderDueBy");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=79)]
        public string ReminderMinutesBeforeStart {
            get {
                return this.reminderMinutesBeforeStartField;
            }
            set {
                this.reminderMinutesBeforeStartField = value;
                this.RaisePropertyChanged("ReminderMinutesBeforeStart");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=80)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Attendee[] RequiredAttendees {
            get {
                return this.requiredAttendeesField;
            }
            set {
                this.requiredAttendeesField = value;
                this.RaisePropertyChanged("RequiredAttendees");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=81)]
        [System.Xml.Serialization.XmlArrayItemAttribute(IsNullable=false)]
        public Attendee[] Resources {
            get {
                return this.resourcesField;
            }
            set {
                this.resourcesField = value;
                this.RaisePropertyChanged("Resources");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=82)]
        public string RetentionDate {
            get {
                return this.retentionDateField;
            }
            set {
                this.retentionDateField = value;
                this.RaisePropertyChanged("RetentionDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=83)]
        public string Schema {
            get {
                return this.schemaField;
            }
            set {
                this.schemaField = value;
                this.RaisePropertyChanged("Schema");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=84)]
        public string Sensitivity {
            get {
                return this.sensitivityField;
            }
            set {
                this.sensitivityField = value;
                this.RaisePropertyChanged("Sensitivity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=85)]
        public string Size {
            get {
                return this.sizeField;
            }
            set {
                this.sizeField = value;
                this.RaisePropertyChanged("Size");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=86)]
        public string Start {
            get {
                return this.startField;
            }
            set {
                this.startField = value;
                this.RaisePropertyChanged("Start");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=87)]
        public StartTimeZone StartTimeZone {
            get {
                return this.startTimeZoneField;
            }
            set {
                this.startTimeZoneField = value;
                this.RaisePropertyChanged("StartTimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=88)]
        public string StoreEntryId {
            get {
                return this.storeEntryIdField;
            }
            set {
                this.storeEntryIdField = value;
                this.RaisePropertyChanged("StoreEntryId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=89)]
        public string Subject {
            get {
                return this.subjectField;
            }
            set {
                this.subjectField = value;
                this.RaisePropertyChanged("Subject");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=90)]
        public string TextBody {
            get {
                return this.textBodyField;
            }
            set {
                this.textBodyField = value;
                this.RaisePropertyChanged("TextBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=91)]
        public string TimeZone {
            get {
                return this.timeZoneField;
            }
            set {
                this.timeZoneField = value;
                this.RaisePropertyChanged("TimeZone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=92)]
        public UniqueBody UniqueBody {
            get {
                return this.uniqueBodyField;
            }
            set {
                this.uniqueBodyField = value;
                this.RaisePropertyChanged("UniqueBody");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=93)]
        public string WebClientEditFormQueryString {
            get {
                return this.webClientEditFormQueryStringField;
            }
            set {
                this.webClientEditFormQueryStringField = value;
                this.RaisePropertyChanged("WebClientEditFormQueryString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=94)]
        public string WebClientReadFormQueryString {
            get {
                return this.webClientReadFormQueryStringField;
            }
            set {
                this.webClientReadFormQueryStringField = value;
                this.RaisePropertyChanged("WebClientReadFormQueryString");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=95)]
        public string When {
            get {
                return this.whenField;
            }
            set {
                this.whenField = value;
                this.RaisePropertyChanged("When");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=96)]
        public string AllowedResponseActions {
            get {
                return this.allowedResponseActionsField;
            }
            set {
                this.allowedResponseActionsField = value;
                this.RaisePropertyChanged("AllowedResponseActions");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=97)]
        public string EffectiveRights {
            get {
                return this.effectiveRightsField;
            }
            set {
                this.effectiveRightsField = value;
                this.RaisePropertyChanged("EffectiveRights");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=98)]
        public string IsOrganized {
            get {
                return this.isOrganizedField;
            }
            set {
                this.isOrganizedField = value;
                this.RaisePropertyChanged("IsOrganized");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=99)]
        public string LocalId {
            get {
                return this.localIdField;
            }
            set {
                this.localIdField = value;
                this.RaisePropertyChanged("LocalId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=100)]
        public string RequestorId {
            get {
                return this.requestorIdField;
            }
            set {
                this.requestorIdField = value;
                this.RaisePropertyChanged("RequestorId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=101)]
        public string RequestorLogin {
            get {
                return this.requestorLoginField;
            }
            set {
                this.requestorLoginField = value;
                this.RaisePropertyChanged("RequestorLogin");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(TypeName="AppointmentTopElmt", Namespace="http://siebel.com/marketing/IntegrationSEI")]
    public partial class AppointmentTopElmt1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Appointment1 appointmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Appointment1 Appointment {
            get {
                return this.appointmentField;
            }
            set {
                this.appointmentField = value;
                this.RaisePropertyChanged("Appointment");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/SEI%20User")]
    public partial class SEIUserOutput : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string errorCodeField;
        
        private string errorTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorText {
            get {
                return this.errorTextField;
            }
            set {
                this.errorTextField = value;
                this.RaisePropertyChanged("ErrorText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3761.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://www.siebel.com/xml/SEI%20User")]
    public partial class SEIUserOutputTopElmt : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SEIUserOutput sEIUserOutputField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SEIUserOutput SEIUserOutput {
            get {
                return this.sEIUserOutputField;
            }
            set {
                this.sEIUserOutputField = value;
                this.RaisePropertyChanged("SEIUserOutput");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SEI_spcIntegration_spcExchangeChannel : SEI.SiebelIntegrationSEI.SEI_spcIntegration_spcExchange, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SEI_spcIntegration_spcExchangeClient : System.ServiceModel.ClientBase<SEI.SiebelIntegrationSEI.SEI_spcIntegration_spcExchange>, SEI.SiebelIntegrationSEI.SEI_spcIntegration_spcExchange {
        
        public SEI_spcIntegration_spcExchangeClient() {
        }
        
        public SEI_spcIntegration_spcExchangeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SEI_spcIntegration_spcExchangeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SEI_spcIntegration_spcExchangeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SEI_spcIntegration_spcExchangeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public SEI.SiebelIntegrationSEI.AppointmentTopElmt DeleteAppointment(string ExchangeId, string SiebelId) {
            return base.Channel.DeleteAppointment(ExchangeId, SiebelId);
        }
        
        public System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.AppointmentTopElmt> DeleteAppointmentAsync(string ExchangeId, string SiebelId) {
            return base.Channel.DeleteAppointmentAsync(ExchangeId, SiebelId);
        }
        
        public SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt InsertSEIUser(string pUserid, string pEmail) {
            return base.Channel.InsertSEIUser(pUserid, pEmail);
        }
        
        public System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt> InsertSEIUserAsync(string pUserid, string pEmail) {
            return base.Channel.InsertSEIUserAsync(pUserid, pEmail);
        }
        
        public SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt DeleteSEIUser(string pUserid) {
            return base.Channel.DeleteSEIUser(pUserid);
        }
        
        public System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt> DeleteSEIUserAsync(string pUserid) {
            return base.Channel.DeleteSEIUserAsync(pUserid);
        }
        
        public SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt ChangeActStatus(string pActionId, string pNewStatus) {
            return base.Channel.ChangeActStatus(pActionId, pNewStatus);
        }
        
        public System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.SEIUserOutputTopElmt> ChangeActStatusAsync(string pActionId, string pNewStatus) {
            return base.Channel.ChangeActStatusAsync(pActionId, pNewStatus);
        }
        
        public SEI.SiebelIntegrationSEI.AppointmentTopElmt NewAppointment(SEI.SiebelIntegrationSEI.AppointmentTopElmt1 ExchangeAppointmentIn) {
            return base.Channel.NewAppointment(ExchangeAppointmentIn);
        }
        
        public System.Threading.Tasks.Task<SEI.SiebelIntegrationSEI.AppointmentTopElmt> NewAppointmentAsync(SEI.SiebelIntegrationSEI.AppointmentTopElmt1 ExchangeAppointmentIn) {
            return base.Channel.NewAppointmentAsync(ExchangeAppointmentIn);
        }
    }
}
